# Generated by Django 4.2.6 on 2023-10-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_alter_tablemodel_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablemodel',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
    ]
