# Generated by Django 4.2.6 on 2023-10-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='service_fee',
            field=models.DecimalField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], decimal_places=2, default=0, max_digits=5, verbose_name='Service Fee'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In process'), ('payed', 'Payed'), ('done', 'Done')], default='new', max_length=255, verbose_name='Status'),
        ),
    ]
