# Generated by Django 4.2.6 on 2023-10-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_ordermodel_service_fee_alter_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='service_fee',
            field=models.PositiveSmallIntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], default=0, verbose_name='Service Fee'),
        ),
    ]
