# Generated by Django 4.2.6 on 2023-11-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_alter_usermodel_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
