# Generated by Django 4.2.6 on 2023-10-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_tablemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'SuperAdmin'), ('admin', 'Admin'), ('waiter', 'Waiter'), ('cashier', 'Cashier'), ('cook', 'Cook')], default='waiter', max_length=255, verbose_name='User type'),
        ),
    ]
