# Generated by Django 4.2.6 on 2023-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_companymodel_is_active_paymentmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Weight'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram')], default='piece', max_length=255, verbose_name='Unit'),
        ),
    ]
