from . import help
from . import start
from . import login
from . import adminWorkerList
from . import adminWorker
from . import workerDetail
from . import productList
from . import productAdd
from . import productDetail
from . import tableList
from . import tableDetail
from . import addTable
from . import orderList
from . import addOrder
from . import orderDetail
from . import tableOrder
from . import statics
from . import cookOrderList
from . import logout
from . import echo
